### ISSUE TITLE
你好，我有一个问题。

### ISSUE THREAD

**Issue by gesions** [marc-harry/kafka-sample#1]
我下载了一个你的这个项目，但我发现Configuration下面定义的TopicNames，而且还是enum。我有点不理解为什么会把这个定义到这个类库里面。因为有可能我会需要用到不同的topic

**Comment by marc-harry** [comment]
This repo is just a sample project using kafka and another library called MHCore.Kafka that I wrote. The enum defined in this project just has topics I was using in this sample but you can change or even remove the enum in your project.

**Comment by cag123anson** [comment]
> 此仓库只是使用kafka和我编写的另一个名为MHCore.Kafka的库的示例项目。该项目中定义的枚举仅包含本示例中使用的主题，但是您可以更改甚至删除项目中的枚举。

**Comment by gesions** [comment]
> This repo is just a sample project using kafka and another library called MHCore.Kafka that I wrote. The enum defined in this project just has topics I was using in this sample but you can change or even remove the enum in your project.

Thank you, lol!
